create table if not exists problems (
    id bigint generated by default as identity primary key,
    answer text not null,
    category varchar(255) not null,
    constraints_json text,
    examples_json text,
    html text not null,
    mode varchar(255) not null,
    problem_number integer not null,
    question varchar(2000) not null,
    solution_json text,
    stage varchar(255) not null,
    starter_code text,
    title varchar(255) not null,
    validation_json text,
    constraint uk_problems_category_number unique (category, problem_number)
);

create table if not exists problem_hints (
    problem_id bigint not null,
    hint varchar(2000),
    hint_order integer not null,
    primary key (problem_id, hint_order),
    constraint fk_problem_hints_problem
        foreign key (problem_id) references problems (id)
);

create table if not exists learning_progress (
    id bigint generated by default as identity primary key,
    attempts integer not null,
    learner_key varchar(100) not null,
    solved boolean not null,
    updated_at timestamp(6) with time zone not null,
    problem_id bigint not null,
    constraint uk_progress_learner_problem unique (learner_key, problem_id),
    constraint fk_progress_problem
        foreign key (problem_id) references problems (id)
);
